routes/web.php
<?php

use \App\Http\Controllers\Web\CashBookController;
use \App\Http\Controllers\Web\CostController;
use App\Http\Controllers\Web\LogActivityController;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\InMailController;
use App\Http\Controllers\Web\OutMailController;
use \App\Http\Controllers\Web\RegistrationCostController;
use App\Http\Controllers\Web\SantriController;
use \App\Http\Controllers\Web\SyahriahController;
use App\Http\Controllers\Web\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false
]);

Route::group(['middleware' => 'auth'], function () {
    Route::get('home', [HomeController::class, 'index'])->name('home');
    Route::resource('santri', SantriController::class);
    Route::resource('pengguna', UserController::class);
    Route::get('log-aktivitas', [LogActivityController::class, 'index'])->name('logs.index');

    // Biaya Pembayaran Pesantren
    Route::get('biaya', [CostController::class, 'index'])->name('biaya.index');
    Route::get('biaya/edit', [CostController::class, 'edit'])->name('biaya.edit');
    Route::patch('biaya/edit', [CostController::class, 'update'])->name('biaya.update');

    // Pembayaran Pendaftaran Santri
    Route::get('pembayaran-pendaftaran', [RegistrationCostController::class, 'index'])->name('registration.index');
    Route::get('pembayaran-pendaftaran/create', [RegistrationCostController::class, 'create'])->name('registration.create');
    Route::post('pembayaran-pendaftaran', [RegistrationCostController::class, 'store'])->name('registration.store');
    Route::get('pembayaran-pendaftaran/print/{id}', [RegistrationCostController::class, 'print'])->name('registration.print');
    Route::delete('pembayaran-pendaftaran/{id}', [RegistrationCostController::class, 'destroy'])->name('registration.destroy');    

    // Syahriah (SPP)
    Route::get('syahriah', [SyahriahController::class, 'index'])->name('syahriah.index');
    Route::get('syahriah/create', [SyahriahController::class, 'create'])->name('syahriah.create');
    Route::post('syahriah', [SyahriahController::class, 'store'])->name('syahriah.store');
    Route::get('syahriah/print/{id}', [SyahriahController::class, 'print'])->name('syahriah.print');
    Route::delete('syahriah/{id}', [SyahriahController::class, 'destroy'])->name('syahriah.destroy');

    // Buku Kas
    Route::get('buku-kas', [CashBookController::class, 'index'])->name('buku-kas.index');
    Route::get('buku-kas/debit/create', [CashBookController::class, 'createDebit'])->name('buku-kas.debit.create');
    Route::post('buku-kas/debit', [CashBookController::class, 'storeDebit'])->name('buku-kas.debit.store');
    Route::get('buku-kas/credit/create', [CashBookController::class, 'createCredit'])->name('buku-kas.credit.create');
    Route::post('buku-kas/credit', [CashBookController::class, 'storeCredit'])->name('buku-kas.credit.store');
    Route::delete('buku-kas/{id}', [CashBookController::class, 'destroy'])->name('buku-kas.destroy');

    Route::resource('surat-masuk', InMailController::class);
    Route::resource('surat-keluar', OutMailController::class);
});

app/Models/OutMail.php
<?php

namespace App\Models;

use App\Traits\Uuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OutMail extends Model
{
    use HasFactory, Uuids;

    public $incrementing = false;
    protected $guarded = [];
}

app/Http/Controllers/Web/OutMailController.php
<?php

namespace App\Http\Controllers\Web;

use App\Helpers\LogActivity;
use App\Http\Controllers\Controller;
use App\Http\Requests\OutMailRequest;
use App\Models\OutMail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Gate;

class OutMailController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data       = OutMail::latest()->paginate(10);
        $keyword    = $request->keyword;
        if ($keyword)
            $data   = OutMail::where('mail_number', 'LIKE', "%$keyword%")
                ->orWhere('mail_date', 'LIKE', "%$keyword%")
                ->orWhere('note', 'LIKE', "%$keyword%")
                ->orWhere('sender', 'LIKE', "%$keyword%")
                ->orWhere('recipient', 'LIKE', "%$keyword%")
                ->latest()
                ->paginate(10);

        return view('out-mail.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('out-mail.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request\OutMailRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OutMailRequest $request)
    {
        $outmail = new OutMail;

        if ($request->hasFile('file_out')) {
            $validatedData = $request->validated();
            $file = $request->file_out;
            $input['file_out'] = 'outmail-'.time().'.'.$file->getClientOriginalExtension();
            $destinationPath = public_path('storage/out-mail');

            File::exists($destinationPath) or File::makeDirectory($destinationPath);

            $destinationPath = public_path('storage/out-mail');
            $file->move($destinationPath, $input['file_out']);
            $validatedData['file_out'] = $input['file_out'];
            $outmail->create($validatedData);
        } else {
            $validatedData = $request->validated();
            $outmail->create($validatedData);
        }

        LogActivity::addToLog('Tambah Surat Keluar');
        return redirect()->route('surat-keluar.index')
            ->with('alert', 'Surat Keluar berhasil ditambahkan.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('out-mail.edit', ['outmail' => OutMail::findOrFail($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request\OutMailRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(OutMailRequest $request, $id)
    {
        $outmail = OutMail::findOrFail($id);

        if ($request->hasFile('file_out')) {
            $validatedData = $request->validated();
            $filePath = public_path('storage/out-mail/'.$outmail->file_out);
            if(File::exists($filePath)) File::delete($filePath);

            $file = $request->file_out;
            $input['file_out'] = 'outmail-'.time().'.'.$file->getClientOriginalExtension();
            $destinationPath = public_path('storage/out-mail');
            File::exists($destinationPath) or File::makeDirectory($destinationPath);
            $file->move($destinationPath, $input['file_out']);
            $validatedData['file_out'] = $input['file_out'];
            $outmail->update($validatedData);
        } else {
            $validatedData = $request->validated();
            $outmail->update($validatedData);
        }

        LogActivity::addToLog('Edit Surat Keluar');
        return redirect()->route('surat-keluar.index')
            ->with('alert', 'Surat Keluar berhasil diupdate.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Gate::allows('admin')) {
            $outmail = OutMail::findOrFail($id);
            $filePath = public_path('storage/out-mail/'.$outmail->file_out);
            if(File::exists($filePath)) File::delete($filePath);
            $outmail->delete();

            LogActivity::addToLog('Hapus Surat Keluar');
            return redirect()->route('surat-keluar.index')
                ->with('alert','Surat Keluar berhasil dihapus.');
        }
        abort(403);
    }
}

resources/views/out-mail/create.blade.php
@extends('layouts.home')
@section('title_page','Tambah Data Surat Keluar')
@section('content')

    <form action="{{ route('surat-keluar.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    <div class="form-group">
                        <label for="mail_number">No. Surat</label>
                        <input type="text" class="form-control @error('mail_number') is-invalid @enderror" name="mail_number" value="{{ old('mail_number') }}">
            
                        @error('mail_number')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-sm">
                    <div class="form-group">
                        <label for="mail_date">Tgl. Surat</label>
                        <input type="date" class="form-control @error('mail_date') is-invalid @enderror" name="mail_date" value="{{ old('mail_date') }}">
            
                        @error('mail_date')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-sm">
                    <div class="form-group">
                        <label for="record_date">Tgl. Catat</label>
                        <input type="date" class="form-control @error('record_date') is-invalid @enderror" name="record_date" value="{{ old('record_date') }}">
            
                        @error('record_date')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <div class="form-group">
                        <label for="sender">Pengirim</label>
                        <input type="text" class="form-control @error('sender') is-invalid @enderror" name="sender" value="{{ old('sender') }}">
            
                        @error('sender')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-sm">
                    <div class="form-group">
                        <label for="recipient">Penerima</label>
                        <input type="text" class="form-control @error('recipient') is-invalid @enderror" name="recipient" value="{{ old('recipient') }}">
            
                        @error('recipient')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-sm">
                    <div class="form-group">
                        <label for="note">Keterangan</label>
                        <textarea class="form-control @error('note') is-invalid @enderror" name="note">{{ old('note') }}</textarea>
            
                        @error('note')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <div class="form-group">
                        <label for="file_out">File</label>
                        <input type="file" class="form-control-file @error('file_out') is-invalid @enderror" name="file_out" value="{{ old('file_out') }}">
                        <span class="text-small text-danger font-italic">File extension only: jpg, jpeg, png, doc, docx, pdf</span>
            
                        @error('file_out')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <div class="form-group">
                        <button class="btn btn-primary">Tambah</button>
                        <a href="{{ route('surat-keluar.index') }}" class="btn btn-secondary">Kembali</a>
                    </div>
                </div>
            </div>
        </div>
    </form>

@endsection

resources/views/out-mail/edit.blade.php
@extends('layouts.home')
@section('title_page','Edit Data Surat Keluar')
@section('content')

    <form action="{{ route('surat-keluar.update', $outmail->id) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('PATCH')
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    <div class="form-group">
                        <label for="mail_number">No. Surat</label>
                        <input type="text" class="form-control @error('mail_number') is-invalid @enderror" name="mail_number" value="{{ old('mail_number', $outmail->mail_number) }}">
            
                        @error('mail_number')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-sm">
                    <div class="form-group">
                        <label for="mail_date">Tgl. Surat</label>
                        <input type="date" class="form-control @error('mail_date') is-invalid @enderror" name="mail_date" value="{{ old('mail_date', $outmail->mail_date) }}">
            
                        @error('mail_date')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-sm">
                    <div class="form-group">
                        <label for="record_date">Tgl. Catat</label>
                        <input type="date" class="form-control @error('record_date') is-invalid @enderror" name="record_date" value="{{ old('record_date', $outmail->record_date) }}">
            
                        @error('record_date')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <div class="form-group">
                        <label for="sender">Pengirim</label>
                        <input type="text" class="form-control @error('sender') is-invalid @enderror" name="sender" value="{{ old('sender', $outmail->sender) }}">
            
                        @error('sender')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-sm">
                    <div class="form-group">
                        <label for="recipient">Penerima</label>
                        <input type="text" class="form-control @error('recipient') is-invalid @enderror" name="recipient" value="{{ old('recipient', $outmail->recipient) }}">
            
                        @error('recipient')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="col-sm">
                    <div class="form-group">
                        <label for="note">Keterangan</label>
                        <textarea class="form-control @error('note') is-invalid @enderror" name="note">{{ old('note', $outmail->note) }}</textarea>
            
                        @error('note')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <div class="form-group">
                        <label for="file_out">File</label>
                        <input type="file" class="form-control-file @error('file_out') is-invalid @enderror" name="file_out" value="{{ old('file_out') }}">
                        <span class="text-small text-danger font-italic">File extension only: jpg, jpeg, png, doc, docx, pdf</span>
            
                        @error('file_out')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <div class="form-group">
                        <button class="btn btn-primary">Update</button>
                        <a href="{{ route('surat-keluar.index') }}" class="btn btn-secondary">Kembali</a>
                    </div>
                </div>
            </div>
        </div>
    </form>

@endsection

resources/views/out-mail/index.blade.php
@extends('layouts.home')
@section('title_page','Data Surat Keluar')
@section('content')

    @if (Session::has('alert'))
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ Session('alert') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <div class="row">
        <div class="col-md-8">
            <a href="{{ route('surat-keluar.create') }}" class="btn btn-primary">Tambah Surat Keluar</a><br><br>
        </div>
        <div class="col-md-4 mb-3">
            <form action="#" class="flex-sm">
                <div class="input-group">
                    <input type="text" name="keyword" class="form-control" placeholder="Search" value="{{ Request::get('keyword') }}">
                    <div class="input-group-append">
                        <button class="btn btn-primary mr-2 rounded-right" type="submit"><i class="fas fa-search"></i></button>
                        <button onclick="window.location.href='{{ route('surat-keluar.index') }}'" type="button" class="btn btn-md btn-secondary rounded"><i class="fas fa-sync-alt"></i></button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-hover table-bordered">
            <thead>
                <tr align="center">
                    <th width="5%">No</th>
                    <th>No. Surat</th>
                    <th>Tgl. Surat</th>
                    <th>Keterangan</th>
                    <th>Pengirim</th>
                    <th>Penerima</th>
                    <th>Tgl. Catat</th>
                    <th>File</th>
                    <th width="13%">Action</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($data as $outmail => $result)
                    <tr>
                        <td>{{ $outmail + $data->firstitem() }}</td>
                        <td>{{ $result->mail_number }}</td>
                        <td>{{ $result->mail_date }}</td>
                        <td>{{ $result->note }}</td>
                        <td>{{ $result->sender }}</td>
                        <td>{{ $result->recipient }}</td>
                        <td>{{ $result->record_date }}</td>
                        <td>
                            @if ($result->file_out == null)
                                <small class="text-warning">No File</small>
                            @else
                                <a href="javascript:void(0)" class="text-info" id="file-out" onclick="viewFile('{{ $result->file_out }}')" data-toggle="modal" data-target="#modalFileOut">{{ $result->file_out }}</a>
                            @endif
                        </td>
                        <td align="center">
                            <a href="{{ route('surat-keluar.edit', $result->id) }}" type="button" class="btn btn-sm btn-info"><i class="fas fa-pen"></i></a>
                            @if (Auth::user()->role == 'Administrator')
                                <a href="javascript:void(0)" id="btn-delete" class="btn btn-sm btn-danger" onclick="deleteData('{{ $result->id }}')" data-toggle="modal" data-target="#deleteSuratModal"><i class="fas fa-trash"></i></a>
                            @endif
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7">Tidak ada data.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    <div class="mt-2 float-left">
        <span class="ml-3">Data Keseluruhan: <span class="text-primary font-weight-bold">{{ DB::table('out_mails')->count() }}</span> Surat Keluar tercatat.</span>
    </div>
    <div class="mt-3 float-right">
        {{ $data->links() }}
    </div>

@endsection

@section('modal')
    <!-- Modal Delete -->
    <div class="modal fade" id="deleteSuratModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <form action="javascript:void(0)" id="deleteForm" method="post">
                @method('DELETE')
                @csrf
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="vcenter">Hapus Surat Keluar</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Apakah anda yakin?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                        <button type="submit" onclick="formSubmit()" class="btn btn-danger">Hapus</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <!-- Modal File In -->
    <div class="modal fade" id="modalFileOut" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content" style="max-width: max-content; width: 690px; height: 610px">
                <div class="modal-header">
                    <h4 class="modal-title" id="vcenter">Tampil File Surat Keluar</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <embed src="" id="embed-file" width="600" height="500" alt="pdf" />
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        function viewFile(data) {
            let url = window.location.origin+'/storage/out-mail/'+data;
            $('#embed-file').attr('src', url);
        }

        function deleteData(id) {
            let url = '{{ route("surat-keluar.destroy", ":id") }}';
            url     = url.replace(':id', id);
            $("#deleteForm").attr('action', url);
        }

        function formSubmit() {
            $("#deleteForm").submit();
        }
    </script>
@endsection